### ISSUE TITLE
求助大佬，上传中断问题

### ISSUE THREAD

**Issue by JIA-Jimmy** [FortuneDayssss/BilibiliUploader#4]
```
Traceback (most recent call last):
  File "upload.py", line 41, in <module>
    thread_pool_workers=4,
  File "/root/bilibiliuploader-0.0.2/bilibiliuploader/bilibiliuploader.py", line 41, in upload
    thread_pool_workers)
  File "/root/bilibiliuploader-0.0.2/bilibiliuploader/core.py", line 303, in upload
    status = status and t_obj.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/bilibiliuploader-0.0.2/bilibiliuploader/core.py", line 220, in upload_video_part
    chunk_total_num
  File "/root/bilibiliuploader-0.0.2/bilibiliuploader/util/retry.py", line 11, in run
    return_value = func(*args, **kwargs)
  File "/root/bilibiliuploader-0.0.2/bilibiliuploader/core.py", line 157, in upload_chunk
    'PHPSESSID': server_file_name
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='upcdn-szhw.bilivideo.com', port=80): Max retries exceeded with url: /vs816/upload3/423902bb0d7c829e9035aa6ea44e6e68/?filename=m200804163bg5q65ukr6jz2jqi3368oc&uip=194.242.x.xx&use_dqp=0&deadline=1596684582&os=bili&profile=ugcfr%2Fpc3&uploadstart=1596540582&uport=57822&uid=530xxxxx&upcdn=172.22.33.245 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55bbd2710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
上传视频中途会中断报错，并且连续好几次都是这样，这是服务器到B站上传cdn的连接问题吗？

**Comment by Wszl** [comment]
Name or service not known 检查自己的网络问题吧，换个dns试试

**Comment by JIA-Jimmy** [comment]
> Name or service not known 检查自己的网络问题吧，换个dns试试

好像这个cdn海外无法解析了，我改host试试看

**Comment by FortuneDayssss** [comment]
> Name or service not known 检查自己的网络问题吧，换个dns试试



> > Name or service not known 检查自己的网络问题吧，换个dns试试
> 
> 好像这个cdn海外无法解析了，我改host试试看

我测试了一下，确实是海外DNS的问题，没有什么太好的解决办法。。。遇到同样的问题我这里测试时只要重新上传就会有大概率成功上传

**Comment by FortuneDayssss** [comment]
可以考虑将DNS服务器临时改为例如1.2.4.8的国内DNS，上传成功后再改回去，可解决问题
